apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "teste-kong-start"
  environment:
    cluster_type: ec2
    public_ip: 54.165.104.135
  annotations:
    github.com/project-slug: veecode-homolog/teste-kong-start
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: terraform-deploy.yml,start_instance.yml,stop_instance.yml,terraform-destroy.yml,deploy_dashboard
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
